### ISSUE TITLE
Uncaught UnsupportedVersionError: Unsupported @Storybook version (undefined). 

### ISSUE THREAD

**Issue by donaldpiret** [InVisionApp/dsm-storybook-cli#30]
Has the latest version with storybook 6 support been published already? Still getting this error when trying to start storybook 6 with the latest version of https://www.npmjs.com/package/@invisionapp/dsm-storybook

**Comment by mortal94** [comment]
Hey @donaldpiret!, we do support Storybook v6 as of version `v0.0.133` of `dsm-storybook`, but according to the error you mentioned in the title of the issue it looks like it has something to do with your current setup and not Storybook v6 because the storybook version stated in the error is `undefined` for some reason.

To be able to help we will need more information about your storybook repo setup, or even better a test repository you can provide that we can replicate the issue with

**Comment by steflen** [comment]
i doubt this is a configuration thing .. having a hard time to figure out which versions are working

[see ](https://github.com/InVisionApp/dsm-storybook-example-library/issues/31)

**Comment by donaldpiret** [comment]
I'm not able to publish the entire repo but will try to see if I can cut it down to something where the issue is easy to see.
Couple of points to note:
- I'm using Vue
- dsm-storybook publish is working
- only the original storybook command is breaking

Do I somehow have to prevent DSM from loading when not running dsm-related commands? From trying to trace the code it looks like the storybook version is being set in an env var by the DSM commands itself?

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
